import {
	ArrowRight,
	ArrowUp,
	Award,
	BadgeCheck,
	Briefcase,
	Building2,
	Check,
	ChevronDown,
	ChevronRight,
	ChevronUp,
	ClipboardList,
	Clock,
	Compass,
	ExternalLink,
	FileCheck2,
	FileText,
	Flag,
	FolderCheck,
	Globe,
	Globe2,
	GraduationCap,
	Heart,
	HeartHandshake,
	Home,
	Languages,
	type LucideIcon,
	Mail,
	Map as MapIcon,
	MapPin,
	Menu,
	MessageCircle,
	MessageSquare,
	Mic,
	Minus,
	MonitorSmartphone,
	Phone,
	PhoneCall,
	Play,
	Plus,
	Quote,
	Route,
	ShieldCheck,
	Stamp,
	UserCheck,
	UserPlus,
	UserRound,
	Users,
	X,
} from "lucide-react";
import type { CSSProperties } from "react";

const MAP: Record<string, LucideIcon> = {
	"arrow-right": ArrowRight,
	"arrow-up": ArrowUp,
	award: Award,
	"badge-check": BadgeCheck,
	briefcase: Briefcase,
	"building-2": Building2,
	check: Check,
	"chevron-down": ChevronDown,
	"chevron-right": ChevronRight,
	"chevron-up": ChevronUp,
	"clipboard-list": ClipboardList,
	clock: Clock,
	compass: Compass,
	"external-link": ExternalLink,
	"file-check-2": FileCheck2,
	"file-text": FileText,
	flag: Flag,
	"folder-check": FolderCheck,
	globe: Globe,
	"globe-2": Globe2,
	"graduation-cap": GraduationCap,
	heart: Heart,
	"heart-handshake": HeartHandshake,
	home: Home,
	languages: Languages,
	mail: Mail,
	map: MapIcon,
	"map-pin": MapPin,
	menu: Menu,
	"message-circle": MessageCircle,
	"message-square": MessageSquare,
	mic: Mic,
	minus: Minus,
	"monitor-smartphone": MonitorSmartphone,
	phone: Phone,
	"phone-call": PhoneCall,
	play: Play,
	plus: Plus,
	quote: Quote,
	route: Route,
	"shield-check": ShieldCheck,
	stamp: Stamp,
	"user-check": UserCheck,
	"user-plus": UserPlus,
	"user-round": UserRound,
	users: Users,
	x: X,
};

export const Icon = ({ n, style }: { n: string; style?: CSSProperties }) => {
	const Cmp = MAP[n];
	if (!Cmp) return null;
	return <Cmp strokeWidth={1.75} style={style} />;
};
